/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Mémoire d'un agent (tenant). Ouverte par une fabrique asynchrone, puis
 * interrogée par `remember`/`recall`/... (toutes des `Promise`).
 */
export declare class Memory {
  /** Ouvre une mémoire persistée de production, chiffrée, avec embedder Candle. */
  static open(options: MemoryOpenOptions): Promise<Memory>
  /** `agent_id` propriétaire de cette mémoire. */
  agent(): string
  /** Mémorise `text` dans une couche (défaut `semantic`). Résout vers l'UUID. */
  remember(text: string, layer?: string | undefined | null): Promise<string>
  /**
   * Ingère une conversation brute : chaque tour devient un souvenir
   * épisodique (`"{role}: {content}"`), en un seul batch. Aucune extraction
   * de faits ici — c'est la consolidation (tâche de fond) qui promeut plus
   * tard des faits durables en couche `semantic` à partir de ces épisodes.
   * Résout vers les UUID créés, dans l'ordre des tours.
   */
  observe(turns: Array<ConversationTurn>): Promise<Array<string>>
  /** Recall temporel sémantique : résout vers un tableau de `Record`. */
  recall(query: string, k?: number | undefined | null, includeProcedural?: boolean | undefined | null, excludeImported?: boolean | undefined | null): Promise<Array<Record>>
  /** Recall limité à une couche mémoire (`short_term`, `episodic`, `procedural`, `semantic`). */
  recallByLayer(query: string, layer: string, k?: number | undefined | null): Promise<Array<Record>>
  /**
   * Recall hybride : vecteur + BM25 (full-text) fusionnés par RRF. Résout vers
   * un tableau de `Record` (le `score` porte le score RRF fusionné).
   */
  recallHybrid(query: string, k?: number | undefined | null, includeProcedural?: boolean | undefined | null, excludeImported?: boolean | undefined | null): Promise<Array<Record>>
  /** Compile a bounded, traceable Markdown context from hybrid recall. */
  compileContext(options: ContextOptions): Promise<ContextBundle>
  /** Invalide (soft-delete) un souvenir par son id. */
  invalidate(id: string): Promise<void>
  /** Supprime physiquement un souvenir (droit à l'effacement). */
  forget(id: string): Promise<void>
  /** Compte des souvenirs valides par couche : résout vers `AgentStats`. */
  stats(): Promise<AgentStats>
  /** Insère ou met à jour une entité du graphe pour cet agent. */
  addGraphEntity(id: string, kind: string, label: string): Promise<void>
  /** Crée ou met à jour une relation orientée du graphe pour cet agent. */
  addGraphEdge(src: string, relation: string, dst: string, weight?: number | undefined | null): Promise<void>
  /** Traverse le graphe depuis `start` : résout vers un tableau d'`Entity`. */
  recallGraph(start: string, maxDepth?: number | undefined | null): Promise<Array<Entity>>
  /**
   * S'abonne en direct aux événements mémoire de `agent_id` (et, si fourni,
   * à une seule couche) — équivalent binding natif du `watch` MCP/REST
   * (ADR-022). `callback` est invoqué avec un [`MemoryEventPayload`] pour
   * chaque événement qui passe le filtre d'isolation.
   *
   * L'isolation est appliquée **côté** `basemyai::MemorySubscription::recv`,
   * jamais déléguée à l'appelant : un `agent_id` qui ne correspond pas à
   * l'agent réellement propriétaire de l'événement ne délivre jamais rien,
   * quel que soit le filtre demandé ici (défense en profondeur — voir
   * `watch_isolates_events_from_other_agents` côté REST/MCP).
   *
   * Résout immédiatement vers un [`WatchHandle`] : appeler `close()` dessus
   * (ou le laisser être garbage-collecté côté JS) arrête le relais et
   * libère la tâche tokio de fond — aucune tâche ne survit indéfiniment
   * sans abonné vivant.
   */
  watch(agentId: string, layer: string | undefined | null, callback: ((arg: MemoryEventPayload) => void)): Promise<WatchHandle>
}

/**
 * Poignée d'abonnement renvoyée par [`Memory::watch`]. Tant qu'elle est
 * vivante (ou jusqu'à `close()`), la tâche de relais tourne en tâche de fond
 * et invoque le callback JS à chaque événement. `close()` est idempotent ;
 * elle est aussi appelée implicitement quand l'objet JS est garbage-collecté
 * (via `Drop`), pour ne jamais fuir de tâche tokio.
 */
export declare class WatchHandle {
  /**
   * Arrête l'abonnement : le callback ne sera plus jamais invoqué après cet
   * appel. Idempotent — un second appel est un no-op.
   */
  close(): void
}

/** Statistiques d'un agent, par couche. */
export interface AgentStats {
  shortTerm: number
  episodic: number
  procedural: number
  semantic: number
  total: number
}

/** Une entité atteinte par une traversée du graphe. */
export interface Entity {
  id: string
  kind: string
  label: string
  depth: number
}

/**
 * Un événement mémoire poussé à un abonné `watch` (ADR-022, live subscriptions
 * côté binding Node). Ne porte jamais le contenu du souvenir — seulement son
 * identité et la nature de la mutation, comme les payloads MCP/REST
 * équivalents ; l'abonné rappelle `recall`/`stats` par `id` s'il veut le détail.
 */
export interface MemoryEventPayload {
  agentId: string
  /**
   * `"remembered"` | `"invalidated"` | `"forgotten"` | `"consolidated"` |
   * `"unknown"` (genre futur non reconnu — `MemoryEventKind` est `#[non_exhaustive]`).
   */
  kind: string
  /** `short_term` | `episodic` | `procedural` | `semantic`. */
  layer: string
  id: string
}

/**
 * Options de production pour ouvrir une mémoire persistée. Tout est
 * optionnel : `path`/`agentId` retombent sur `~/.basemyai/config.toml` /
 * `BASEMYAI_DB_PATH` / `BASEMYAI_AGENT` (même résolution que la CLI) puis sur
 * un défaut intégré (`./basemyai.bmai`, agent `"default"`) ; sans
 * `encryptionKey` ni source configurée, une clé est générée et persistée
 * dans `~/.basemyai/key`. Seul le téléchargement du modèle
 * (`allowModelDownload`) reste soumis à consentement explicite — jamais
 * silencieux (ADR-010).
 */
export interface MemoryOpenOptions {
  path?: string
  agentId?: string
  encryptionKey?: string
  /** `raw` (default for an explicit key) or `passphrase` (Argon2id). */
  credentialMode?: 'raw' | 'passphrase'
  modelPath?: string
  allowModelDownload?: boolean
}

/**
 * Un tour de conversation brut (rôle + contenu) à ingérer via
 * `Memory.observe()`. `role` n'est pas validé : libellé libre (`"user"`,
 * `"assistant"`, `"system"`, ...), simplement reporté dans le texte mémorisé.
 */
export interface ConversationTurn {
  role: string
  content: string
}

/** Un souvenir retourné par `recall`. */
export interface Record {
  id: string
  text: string
  /** `short_term` | `episodic` | `procedural` | `semantic`. */
  layer: string
  /** Similarité cosinus normalisée dans `[0, 1]` (`1` = identique). */
  score: number
  /** Tag wire de provenance. */
  source: string
  /** Provenance typée (ADR-036). */
  trust: string
  /** Inclusive validity start as a Unix UTC timestamp. */
  validFrom: number
  /** Exclusive validity end, when bounded. */
  validUntil?: number
}

export type ContextSourcePolicy = 'allow_all' | 'exclude_imported' | 'user_and_consolidation_only'
export type ContextSectionKind = 'working_context' | 'current_facts' | 'procedures' | 'recent_events' | 'unknown'
export type ContextTemporalStatus = 'current' | 'scheduled' | 'expired' | 'unknown'
export type ExclusionReason = 'source_filtered' | 'not_currently_valid' | 'token_budget' | 'unknown'

export interface ContextOptions {
  query: string
  tokenBudget: number
  candidateLimit?: number
  includeProcedural?: boolean
  sourcePolicy?: ContextSourcePolicy
  explain?: boolean
}

export interface ContextItem {
  text: string
  sourceMemoryIds: Array<string>
  layer: string
  trust: string
  validFrom: number
  validUntil?: number
  temporalStatus: ContextTemporalStatus
  retrievalScore: number
  retrievalRank: number
  estimatedTokens: number
  utilityScore: number
  valuePerToken: number
  freshnessScore: number
}

export interface ContextSection {
  kind: ContextSectionKind
  items: Array<ContextItem>
}

export interface ContextCitation {
  memoryId: string
  section: ContextSectionKind
}

export interface ExcludedMemory {
  memoryId: string
  reason: ExclusionReason
  temporalStatus: ContextTemporalStatus
}

export interface MergedMemory {
  memoryId: string
  representativeMemoryId: string
}

export interface ContextBundle {
  sections: Array<ContextSection>
  rendered: string
  estimatedTokens: number
  compiledAt: number
  totalUtility: number
  citations: Array<ContextCitation>
  merged: Array<MergedMemory>
  excluded: Array<ExcludedMemory>
}
