/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Mémoire d'un agent (tenant). Ouverte par une fabrique asynchrone, puis
 * interrogée par `remember`/`recall`/... (toutes des `Promise`).
 */
export declare class Memory {
  /** Ouvre une mémoire persistée de production, chiffrée, avec embedder Candle. */
  static open(options: MemoryOpenOptions): Promise<Memory>
  /** `agent_id` propriétaire de cette mémoire. */
  agent(): string
  /** Mémorise `text` dans une couche (défaut `semantic`). Résout vers l'UUID. */
  remember(text: string, layer?: string | undefined | null): Promise<string>
  /** Recall temporel sémantique : résout vers un tableau de `Record`. */
  recall(query: string, k?: number | undefined | null): Promise<Array<Record>>
  /** Recall limité à une couche mémoire (`short_term`, `episodic`, `procedural`, `semantic`). */
  recallByLayer(query: string, layer: string, k?: number | undefined | null): Promise<Array<Record>>
  /**
   * Recall hybride : vecteur + BM25 (full-text) fusionnés par RRF. Résout vers
   * un tableau de `Record` (le `score` porte le score RRF fusionné).
   */
  recallHybrid(query: string, k?: number | undefined | null): Promise<Array<Record>>
  /** Invalide (soft-delete) un souvenir par son id. */
  invalidate(id: string): Promise<void>
  /** Supprime physiquement un souvenir (droit à l'effacement). */
  forget(id: string): Promise<void>
  /** Compte des souvenirs valides par couche : résout vers `AgentStats`. */
  stats(): Promise<AgentStats>
  /** Insère ou met à jour une entité du graphe pour cet agent. */
  addGraphEntity(id: string, kind: string, label: string): Promise<void>
  /** Crée ou met à jour une relation orientée du graphe pour cet agent. */
  addGraphEdge(src: string, relation: string, dst: string, weight?: number | undefined | null): Promise<void>
  /** Traverse le graphe depuis `start` : résout vers un tableau d'`Entity`. */
  recallGraph(start: string, maxDepth?: number | undefined | null): Promise<Array<Entity>>
}

/** Statistiques d'un agent, par couche. */
export interface AgentStats {
  shortTerm: number
  episodic: number
  procedural: number
  semantic: number
  total: number
}

/** Une entité atteinte par une traversée du graphe. */
export interface Entity {
  id: string
  kind: string
  label: string
  depth: number
}

/** Options de production pour ouvrir une mémoire persistée. */
export interface MemoryOpenOptions {
  path: string
  agentId: string
  encryptionKey: string
  modelPath?: string
  allowModelDownload?: boolean
}

/** Un souvenir retourné par `recall`. */
export interface Record {
  id: string
  text: string
  /** `short_term` | `episodic` | `procedural` | `semantic`. */
  layer: string
  /** Similarité cosinus normalisée dans `[0, 1]` (`1` = identique). */
  score: number
}
