/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Mémoire d'un agent (tenant). Ouverte par une fabrique asynchrone, puis
 * interrogée par `remember`/`recall`/... (toutes des `Promise`).
 */
export declare class Memory {
  /** Ouvre une mémoire persistée de production, chiffrée, avec embedder Candle. */
  static open(options: MemoryOpenOptions): Promise<Memory>
  /** `agent_id` propriétaire de cette mémoire. */
  agent(): string
  /** Mémorise `text` dans une couche (défaut `semantic`). Résout vers l'UUID. */
  remember(text: string, layer?: string | undefined | null): Promise<string>
  /** Recall temporel sémantique : résout vers un tableau de `Record`. */
  recall(query: string, k?: number | undefined | null, includeProcedural?: boolean | undefined | null, excludeImported?: boolean | undefined | null): Promise<Array<Record>>
  /** Recall limité à une couche mémoire (`short_term`, `episodic`, `procedural`, `semantic`). */
  recallByLayer(query: string, layer: string, k?: number | undefined | null): Promise<Array<Record>>
  /**
   * Recall hybride : vecteur + BM25 (full-text) fusionnés par RRF. Résout vers
   * un tableau de `Record` (le `score` porte le score RRF fusionné).
   */
  recallHybrid(query: string, k?: number | undefined | null, includeProcedural?: boolean | undefined | null, excludeImported?: boolean | undefined | null): Promise<Array<Record>>
  /** Invalide (soft-delete) un souvenir par son id. */
  invalidate(id: string): Promise<void>
  /** Supprime physiquement un souvenir (droit à l'effacement). */
  forget(id: string): Promise<void>
  /** Compte des souvenirs valides par couche : résout vers `AgentStats`. */
  stats(): Promise<AgentStats>
  /** Insère ou met à jour une entité du graphe pour cet agent. */
  addGraphEntity(id: string, kind: string, label: string): Promise<void>
  /** Crée ou met à jour une relation orientée du graphe pour cet agent. */
  addGraphEdge(src: string, relation: string, dst: string, weight?: number | undefined | null): Promise<void>
  /** Traverse le graphe depuis `start` : résout vers un tableau d'`Entity`. */
  recallGraph(start: string, maxDepth?: number | undefined | null): Promise<Array<Entity>>
  /**
   * S'abonne en direct aux événements mémoire de `agent_id` (et, si fourni,
   * à une seule couche) — équivalent binding natif du `watch` MCP/REST
   * (ADR-022). `callback` est invoqué avec un [`MemoryEventPayload`] pour
   * chaque événement qui passe le filtre d'isolation.
   *
   * L'isolation est appliquée **côté** `basemyai::MemorySubscription::recv`,
   * jamais déléguée à l'appelant : un `agent_id` qui ne correspond pas à
   * l'agent réellement propriétaire de l'événement ne délivre jamais rien,
   * quel que soit le filtre demandé ici (défense en profondeur — voir
   * `watch_isolates_events_from_other_agents` côté REST/MCP).
   *
   * Résout immédiatement vers un [`WatchHandle`] : appeler `close()` dessus
   * (ou le laisser être garbage-collecté côté JS) arrête le relais et
   * libère la tâche tokio de fond — aucune tâche ne survit indéfiniment
   * sans abonné vivant.
   */
  watch(agentId: string, layer: string | undefined | null, callback: ((arg: MemoryEventPayload) => void)): Promise<WatchHandle>
}

/**
 * Poignée d'abonnement renvoyée par [`Memory::watch`]. Tant qu'elle est
 * vivante (ou jusqu'à `close()`), la tâche de relais tourne en tâche de fond
 * et invoque le callback JS à chaque événement. `close()` est idempotent ;
 * elle est aussi appelée implicitement quand l'objet JS est garbage-collecté
 * (via `Drop`), pour ne jamais fuir de tâche tokio.
 */
export declare class WatchHandle {
  /**
   * Arrête l'abonnement : le callback ne sera plus jamais invoqué après cet
   * appel. Idempotent — un second appel est un no-op.
   */
  close(): void
}

/** Statistiques d'un agent, par couche. */
export interface AgentStats {
  shortTerm: number
  episodic: number
  procedural: number
  semantic: number
  total: number
}

/** Une entité atteinte par une traversée du graphe. */
export interface Entity {
  id: string
  kind: string
  label: string
  depth: number
}

/**
 * Un événement mémoire poussé à un abonné `watch` (ADR-022, live subscriptions
 * côté binding Node). Ne porte jamais le contenu du souvenir — seulement son
 * identité et la nature de la mutation, comme les payloads MCP/REST
 * équivalents ; l'abonné rappelle `recall`/`stats` par `id` s'il veut le détail.
 */
export interface MemoryEventPayload {
  agentId: string
  /**
   * `"remembered"` | `"invalidated"` | `"forgotten"` | `"consolidated"` |
   * `"unknown"` (genre futur non reconnu — `MemoryEventKind` est `#[non_exhaustive]`).
   */
  kind: string
  /** `short_term` | `episodic` | `procedural` | `semantic`. */
  layer: string
  id: string
}

/** Options de production pour ouvrir une mémoire persistée. */
export interface MemoryOpenOptions {
  path: string
  agentId: string
  encryptionKey?: string
  modelPath?: string
  allowModelDownload?: boolean
}

/** Un souvenir retourné par `recall`. */
export interface Record {
  id: string
  text: string
  /** `short_term` | `episodic` | `procedural` | `semantic`. */
  layer: string
  /** Similarité cosinus normalisée dans `[0, 1]` (`1` = identique). */
  score: number
  /** Tag wire de provenance. */
  source: string
  /** Provenance typée (ADR-036). */
  trust: string
}
